import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./layoutClient";
import { Poppins } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"

const inter = Poppins({ subsets: ['latin'], weight: ["400"] })

export const metadata: Metadata = {
  title: "Verify IDX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <ClientLayout>{children}</ClientLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
